/**********************************************************************
 * WARNING!
 *
 * This file is automatically generated. Do not edit this file directly;
 * instead edit art-data.txt to modify unrandart data, or util/art-data.pl
 * if this file is not being generated to your taste.
 *
 * Ignoring these warnings and editing this file directly will cause you
 * to be hunted down and eaten by dire ravens.
 **********************************************************************/

#include "AppHdr.h"
#include "rltiles/tiledef-unrand.h"

#include "art-enum.h"
#include "rltiles/tiledef-main.h"
#include "rltiles/tiledef-player.h"

int unrandart_to_tile(int unrand)
{
    switch (unrand)
    {
    case UNRAND_SINGING_SWORD:                return TILE_UNRAND_SINGING_SWORD;
    case UNRAND_TROG:                         return TILE_UNRAND_TROG;
    case UNRAND_VARIABILITY:                  return TILE_UNRAND_VARIABILITY;
    case UNRAND_PRUNE:                        return TILE_UNRAND_PRUNE;
    case UNRAND_POWER:                        return TILE_UNRAND_POWER;
    case UNRAND_OLGREB:                       return TILE_UNRAND_OLGREB;
    case UNRAND_WUCAD_MU:                     return TILE_UNRAND_WUCAD_MU;
    case UNRAND_VAMPIRES_TOOTH:               return TILE_UNRAND_VAMPIRES_TOOTH;
    case UNRAND_CURSES:                       return TILE_UNRAND_CURSES;
    case UNRAND_TORMENT:                      return TILE_UNRAND_TORMENT;
    case UNRAND_ZONGULDROK:                   return TILE_UNRAND_ZONGULDROK;
    case UNRAND_CEREBOV:                      return TILE_UNRAND_CEREBOV;
    case UNRAND_DISPATER:                     return TILE_UNRAND_DISPATER;
    case UNRAND_ASMODEUS:                     return TILE_UNRAND_ASMODEUS;
    case UNRAND_FAERIE:                       return TILE_UNRAND_FAERIE;
    case UNRAND_BLOODBANE:                    return TILE_UNRAND_BLOODBANE;
    case UNRAND_FLAMING_DEATH:                return TILE_UNRAND_FLAMING_DEATH;
    case UNRAND_BRILLIANCE:                   return TILE_UNRAND_BRILLIANCE;
    case UNRAND_LEECH:                        return TILE_UNRAND_LEECH;
    case UNRAND_CHILLY_DEATH:                 return TILE_UNRAND_CHILLY_DEATH;
    case UNRAND_MORG:                         return TILE_UNRAND_MORG;
    case UNRAND_FINISHER:                     return TILE_UNRAND_FINISHER;
    case UNRAND_PUNK:                         return TILE_UNRAND_PUNK;
    case UNRAND_ZEPHYR:                       return TILE_UNRAND_ZEPHYR;
    case UNRAND_SKULLCRUSHER:                 return TILE_UNRAND_SKULLCRUSHER;
    case UNRAND_GUARD:                        return TILE_UNRAND_GUARD;
    case UNRAND_ZEALOT_SWORD:                 return TILE_UNRAND_ZEALOT_SWORD;
    case UNRAND_DAMNATION:                    return TILE_UNRAND_DAMNATION;
    case UNRAND_DOOM_KNIGHT:                  return TILE_UNRAND_DOOM_KNIGHT;
    case UNRAND_EOS:                          return TILE_UNRAND_EOS;
    case UNRAND_BOTONO:                       return TILE_UNRAND_BOTONO;
    case UNRAND_OCTOPUS_KING:                 return TILE_UNRAND_OCTOPUS_KING;
    case UNRAND_ARGA:                         return TILE_UNRAND_ARGA;
    case UNRAND_ELEMENTAL_STAFF:              return TILE_UNRAND_ELEMENTAL_STAFF;
    case UNRAND_SNIPER:                       return TILE_UNRAND_SNIPER;
    case UNRAND_PIERCER:                      return TILE_UNRAND_PIERCER;
    case UNRAND_BLOWGUN_ASSASSIN:             return TILE_UNRAND_BLOWGUN_ASSASSIN;
    case UNRAND_WYRMBANE:                     return TILE_UNRAND_WYRMBANE;
    case UNRAND_SPRIGGANS_KNIFE:              return TILE_UNRAND_SPRIGGANS_KNIFE;
    case UNRAND_PLUTONIUM_SWORD:              return TILE_UNRAND_PLUTONIUM_SWORD;
    case UNRAND_UNDEADHUNTER:                 return TILE_UNRAND_UNDEADHUNTER;
    case UNRAND_SNAKEBITE:                    return TILE_UNRAND_SNAKEBITE;
    case UNRAND_ACCURACY:                     return TILE_UNRAND_ACCURACY;
    case UNRAND_CRYSTAL_SPEAR:                return TILE_UNRAND_CRYSTAL_SPEAR;
    case UNRAND_CAPTAIN:                      return TILE_UNRAND_CAPTAIN;
    case UNRAND_STORM_BOW:                    return TILE_UNRAND_STORM_BOW;
    case UNRAND_IGNORANCE:                    return TILE_UNRAND_IGNORANCE;
    case UNRAND_AUGMENTATION:                 return TILE_UNRAND_AUGMENTATION;
    case UNRAND_THIEF:                        return TILE_UNRAND_THIEF;
    case UNRAND_BULLSEYE:                     return TILE_UNRAND_BULLSEYE;
    case UNRAND_DYROVEPREVA:                  return TILE_UNRAND_DYROVEPREVA;
    case UNRAND_BEAR_SPIRIT:                  return TILE_UNRAND_BEAR_SPIRIT;
    case UNRAND_MISFORTUNE:                   return TILE_UNRAND_MISFORTUNE;
    case UNRAND_FLASH:                        return TILE_UNRAND_FLASH;
    case UNRAND_HOOD_ASSASSIN:                return TILE_UNRAND_HOOD_ASSASSIN;
    case UNRAND_LEAR:                         return TILE_UNRAND_LEAR;
    case UNRAND_ZHOR:                         return TILE_UNRAND_ZHOR;
    case UNRAND_SALAMANDER:                   return TILE_UNRAND_SALAMANDER;
    case UNRAND_WAR:                          return TILE_UNRAND_WAR;
    case UNRAND_RESISTANCE:                   return TILE_UNRAND_RESISTANCE;
    case UNRAND_FOLLY:                        return TILE_UNRAND_FOLLY;
    case UNRAND_MAXWELL:                      return TILE_UNRAND_MAXWELL;
    case UNRAND_DRAGONMASK:                   return TILE_UNRAND_DRAGONMASK;
    case UNRAND_NIGHT:                        return TILE_UNRAND_NIGHT;
    case UNRAND_DRAGON_KING:                  return TILE_UNRAND_DRAGON_KING;
    case UNRAND_ALCHEMIST:                    return TILE_UNRAND_ALCHEMIST;
    case UNRAND_FENCERS:                      return TILE_UNRAND_FENCERS;
    case UNRAND_STARLIGHT:                    return TILE_UNRAND_STARLIGHT;
    case UNRAND_RATSKIN_CLOAK:                return TILE_UNRAND_RATSKIN_CLOAK;
    case UNRAND_GONG:                         return TILE_UNRAND_GONG;
    case UNRAND_AIR:                          return TILE_UNRAND_AIR;
    case UNRAND_SHADOWS:                      return TILE_UNRAND_SHADOWS;
    case UNRAND_CEKUGOB:                      return TILE_UNRAND_CEKUGOB;
    case UNRAND_FOUR_WINDS:                   return TILE_UNRAND_FOUR_WINDS;
    case UNRAND_BLOODLUST:                    return TILE_UNRAND_BLOODLUST;
    case UNRAND_HARE:                         return TILE_UNRAND_HARE;
    case UNRAND_TORTOISE:                     return TILE_UNRAND_TORTOISE;
    case UNRAND_MAGE:                         return TILE_UNRAND_MAGE;
    case UNRAND_SHIELDING:                    return TILE_UNRAND_SHIELDING;
    case UNRAND_RCLOUDS:                      return TILE_UNRAND_RCLOUDS;
    case UNRAND_PONDERING:                    return TILE_UNRAND_PONDERING;
    case UNRAND_DEMON_AXE:                    return TILE_UNRAND_DEMON_AXE;
    case UNRAND_LIGHTNING_SCALES:             return TILE_UNRAND_LIGHTNING_SCALES;
    case UNRAND_BLACK_KNIGHT_HORSE:           return TILE_UNRAND_BLACK_KNIGHT_HORSE;
    case UNRAND_VITALITY:                     return TILE_UNRAND_VITALITY;
    case UNRAND_AUTUMN_KATANA:                return TILE_UNRAND_AUTUMN_KATANA;
    case UNRAND_DEVASTATOR:                   return TILE_UNRAND_DEVASTATOR;
    case UNRAND_DRAGONSKIN:                   return TILE_UNRAND_DRAGONSKIN;
    case UNRAND_OCTOPUS_KING_RING:            return TILE_UNRAND_OCTOPUS_KING_RING;
    case UNRAND_WOE:                          return TILE_UNRAND_WOE;
    case UNRAND_MOON_TROLL_LEATHER_ARMOUR:    return TILE_UNRAND_MOON_TROLL_LEATHER_ARMOUR;
    case UNRAND_FINGER_AMULET:                return TILE_UNRAND_FINGER_AMULET;
    case UNRAND_SPIDER:                       return TILE_UNRAND_SPIDER;
    case UNRAND_DARK_MAUL:                    return TILE_UNRAND_DARK_MAUL;
    case UNRAND_HIGH_COUNCIL:                 return TILE_UNRAND_HIGH_COUNCIL;
    case UNRAND_ARC_BLADE:                    return TILE_UNRAND_ARC_BLADE;
    case UNRAND_SPELLBINDER:                  return TILE_UNRAND_SPELLBINDER;
    case UNRAND_ORDER:                        return TILE_UNRAND_ORDER;
    case UNRAND_FIRESTARTER:                  return TILE_UNRAND_FIRESTARTER;
    case UNRAND_ORANGE_CRYSTAL_PLATE_ARMOUR:  return TILE_UNRAND_ORANGE_CRYSTAL_PLATE_ARMOUR;
    case UNRAND_MAJIN:                        return TILE_UNRAND_MAJIN;
    case UNRAND_GYRE:                         return TILE_UNRAND_GYRE;
    case UNRAND_ETHERIC_CAGE:                 return TILE_UNRAND_ETHERIC_CAGE;
    case UNRAND_ETERNAL_TORMENT:              return TILE_UNRAND_ETERNAL_TORMENT;
    case UNRAND_VINES:                        return TILE_UNRAND_VINES;
    case UNRAND_KRYIAS:                       return TILE_UNRAND_KRYIAS;
    case UNRAND_FROSTBITE:                    return TILE_UNRAND_FROSTBITE;
    case UNRAND_TALOS:                        return TILE_UNRAND_TALOS;
    case UNRAND_WARLOCK_MIRROR:               return TILE_UNRAND_WARLOCK_MIRROR;
    case UNRAND_INVISIBILITY:                 return TILE_UNRAND_INVISIBILITY;
    case UNRAND_THERMIC_ENGINE:               return TILE_UNRAND_THERMIC_ENGINE;
    case UNRAND_RIFT:                         return TILE_UNRAND_RIFT;
    case UNRAND_BATTLE:                       return TILE_UNRAND_BATTLE;
    case UNRAND_EMBRACE:                      return TILE_UNRAND_EMBRACE;
    case UNRAND_SEVEN_LEAGUE_BOOTS:           return TILE_UNRAND_SEVEN_LEAGUE_BOOTS;
    case UNRAND_POWER_GLOVES:                 return TILE_UNRAND_POWER_GLOVES;
    case UNRAND_DREAMSHARD_NECKLACE:          return TILE_UNRAND_DREAMSHARD_NECKLACE;
    case UNRAND_DELATRAS_GLOVES:              return TILE_UNRAND_DELATRAS_GLOVES;
    case UNRAND_WOODCUTTERS_AXE:              return TILE_UNRAND_WOODCUTTERS_AXE;
    case UNRAND_THROATCUTTER:                 return TILE_UNRAND_THROATCUTTER;
    case UNRAND_MEEK:                         return TILE_UNRAND_MEEK;
    case UNRAND_CONDEMNATION:                 return TILE_UNRAND_CONDEMNATION;
    case UNRAND_ELEMENTAL_VULNERABILITY:      return TILE_UNRAND_ELEMENTAL_VULNERABILITY;
    case UNRAND_MOUNTAIN_BOOTS:               return TILE_UNRAND_MOUNTAIN_BOOTS;
    case UNRAND_LOCHABER_AXE:                 return TILE_UNRAND_LOCHABER_AXE;
    case UNRAND_HERMITS_PENDANT:              return TILE_UNRAND_HERMITS_PENDANT;
    case UNRAND_SLICK_SLIPPERS:               return TILE_UNRAND_SLICK_SLIPPERS;
    case UNRAND_FORCE_LANCE:                  return TILE_UNRAND_FORCE_LANCE;
    case UNRAND_HOLY_AXE:                     return TILE_UNRAND_HOLY_AXE;
    case UNRAND_VICTORY:                      return TILE_UNRAND_VICTORY;
    case UNRAND_STORM_QUEEN:                  return TILE_UNRAND_STORM_QUEEN;
    case UNRAND_DREAMDUST_NECKLACE:           return TILE_UNRAND_DREAMDUST_NECKLACE;
    case UNRAND_MULE:                         return TILE_UNRAND_MULE;
    default: return 0;
    }
}

int unrandart_to_doll_tile(int unrand)
{
    switch (unrand)
    {
    // ARM
    case UNRAND_WAR:                          return TILEP_ARM_GLOVE_BLACK;
    case UNRAND_FENCERS:                      return TILEP_ARM_GLOVE_WHITE;
    case UNRAND_POWER_GLOVES:                 return TILEP_ARM_GLOVE_BROWN;
    case UNRAND_DELATRAS_GLOVES:              return TILEP_ARM_GLOVE_BLUE;
    // BODY
    case UNRAND_FAERIE:                       return TILEP_BODY_FAERIE_DRAGON_ARMOUR;
    case UNRAND_AUGMENTATION:                 return TILEP_BODY_ROBE_AUGMENTATION;
    case UNRAND_MISFORTUNE:                   return TILEP_BODY_ROBE_MISFORTUNE;
    case UNRAND_LEAR:                         return TILEP_BODY_LEARS_HAUBERK;
    case UNRAND_ZHOR:                         return TILEP_BODY_ZHOR;
    case UNRAND_SALAMANDER:                   return TILEP_BODY_LEATHER_RED;
    case UNRAND_FOLLY:                        return TILEP_BODY_ROBE_FOLLY;
    case UNRAND_MAXWELL:                      return TILEP_BODY_MAXWELL;
    case UNRAND_NIGHT:                        return TILEP_BODY_ROBE_OF_NIGHT;
    case UNRAND_DRAGON_KING:                  return TILEP_BODY_DRAGONARM_GOLD;
    case UNRAND_RCLOUDS:                      return TILEP_BODY_ROBE_CLOUDS;
    case UNRAND_MOON_TROLL_LEATHER_ARMOUR:    return TILEP_BODY_MOON_TROLL_LEATHER_ARMOUR;
    case UNRAND_ORANGE_CRYSTAL_PLATE_ARMOUR:  return TILEP_BODY_ORANGE_CRYSTAL;
    case UNRAND_VINES:                        return TILEP_BODY_VINES;
    case UNRAND_KRYIAS:                       return TILEP_BODY_KRYIAS;
    case UNRAND_TALOS:                        return TILEP_BODY_TALOS;
    case UNRAND_EMBRACE:                      return TILEP_BODY_BPLATE_GREEN;
    case UNRAND_VICTORY:                      return TILEP_BODY_ARWEN;
    // BOOTS
    case UNRAND_LIGHTNING_SCALES:             return TILEP_BOOTS_LIGHTNING_SCALES;
    case UNRAND_BLACK_KNIGHT_HORSE:           return TILEP_BOOTS_BLACK_KNIGHT;
    case UNRAND_SPIDER:                       return TILEP_BOOTS_SPIDER;
    case UNRAND_SEVEN_LEAGUE_BOOTS:           return TILEP_BOOTS_SEVEN_LEAGUE_BOOTS;
    case UNRAND_MOUNTAIN_BOOTS:               return TILEP_BOOTS_SPIDER;
    case UNRAND_SLICK_SLIPPERS:               return TILEP_BOOTS_SLIPPERS;
    // CLOAK
    case UNRAND_THIEF:                        return TILEP_CLOAK_BLACK;
    case UNRAND_FLASH:                        return TILEP_CLOAK_RED;
    case UNRAND_STARLIGHT:                    return TILEP_CLOAK_WHITE;
    case UNRAND_RATSKIN_CLOAK:                return TILEP_CLOAK_RATSKIN_CLOAK;
    case UNRAND_DRAGONSKIN:                   return TILEP_CLOAK_DRAGONSKIN_CLOAK;
    // HAND1
    case UNRAND_SINGING_SWORD:                return TILEP_HAND1_SINGING_SWORD;
    case UNRAND_TROG:                         return TILEP_HAND1_AXE_TROG;
    case UNRAND_VARIABILITY:                  return TILEP_HAND1_MACE_OF_VARIABILITY;
    case UNRAND_PRUNE:                        return TILEP_HAND1_GLAIVE_OF_PRUNE;
    case UNRAND_POWER:                        return TILEP_HAND1_SWORD_OF_POWER;
    case UNRAND_OLGREB:                       return TILEP_HAND1_OLGREB;
    case UNRAND_VAMPIRES_TOOTH:               return TILEP_HAND1_VAMPIRES_TOOTH;
    case UNRAND_CURSES:                       return TILEP_HAND1_FINISHER;
    case UNRAND_TORMENT:                      return TILEP_HAND1_SCEPTRE_OF_TORMENT;
    case UNRAND_ZONGULDROK:                   return TILEP_HAND1_ZONGULDROK;
    case UNRAND_CEREBOV:                      return TILEP_HAND1_SWORD_TWIST;
    case UNRAND_ASMODEUS:                     return TILEP_HAND1_ASMODEUS;
    case UNRAND_BLOODBANE:                    return TILEP_HAND1_BLOODBANE;
    case UNRAND_FLAMING_DEATH:                return TILEP_HAND1_FLAMING_DEATH;
    case UNRAND_BRILLIANCE:                   return TILEP_HAND1_MACE_OF_BRILLIANCE;
    case UNRAND_LEECH:                        return TILEP_HAND1_LEECH;
    case UNRAND_CHILLY_DEATH:                 return TILEP_HAND1_CHILLY_DEATH;
    case UNRAND_MORG:                         return TILEP_HAND1_MORG;
    case UNRAND_FINISHER:                     return TILEP_HAND1_FINISHER;
    case UNRAND_PUNK:                         return TILEP_HAND1_PUNK;
    case UNRAND_ZEPHYR:                       return TILEP_HAND1_ZEPHYR;
    case UNRAND_SKULLCRUSHER:                 return TILEP_HAND1_SKULLCRUSHER;
    case UNRAND_GUARD:                        return TILEP_HAND1_GLAIVE_OF_THE_GUARD;
    case UNRAND_ZEALOT_SWORD:                 return TILEP_HAND1_ZEALOT_SWORD;
    case UNRAND_DAMNATION:                    return TILEP_HAND1_FIERY_DEVIL;
    case UNRAND_DOOM_KNIGHT:                  return TILEP_HAND1_DOOM_KNIGHT;
    case UNRAND_EOS:                          return TILEP_HAND1_EOS;
    case UNRAND_BOTONO:                       return TILEP_HAND1_BOTONO;
    case UNRAND_OCTOPUS_KING:                 return TILEP_HAND1_TRIDENT_OCTOPUS_KING;
    case UNRAND_ARGA:                         return TILEP_HAND1_ARGA;
    case UNRAND_ELEMENTAL_STAFF:              return TILEP_HAND1_ELEMENTAL_STAFF;
    case UNRAND_SNIPER:                       return TILEP_HAND1_SNIPER;
    case UNRAND_PIERCER:                      return TILEP_HAND1_GREAT_BOW;
    case UNRAND_BLOWGUN_ASSASSIN:             return TILEP_HAND1_BLOWGUN;
    case UNRAND_WYRMBANE:                     return TILEP_HAND1_WYRMBANE;
    case UNRAND_SPRIGGANS_KNIFE:              return TILEP_HAND1_SPRIGGANS_KNIFE;
    case UNRAND_PLUTONIUM_SWORD:              return TILEP_HAND1_PLUTONIUM_SWORD;
    case UNRAND_UNDEADHUNTER:                 return TILEP_HAND1_UNDEADHUNTER;
    case UNRAND_SNAKEBITE:                    return TILEP_HAND1_SNAKEBITE;
    case UNRAND_ACCURACY:                     return TILEP_HAND1_KNIFE_OF_ACCURACY;
    case UNRAND_CRYSTAL_SPEAR:                return TILEP_HAND1_CRYSTAL_SPEAR;
    case UNRAND_CAPTAIN:                      return TILEP_HAND1_CAPT_CUTLASS;
    case UNRAND_STORM_BOW:                    return TILEP_HAND1_STORM_BOW;
    case UNRAND_DEMON_AXE:                    return TILEP_HAND1_DEMON_AXE;
    case UNRAND_AUTUMN_KATANA:                return TILEP_HAND1_KATANA_SLANT;
    case UNRAND_DEVASTATOR:                   return TILEP_HAND1_SHILLELAGH;
    case UNRAND_WOE:                          return TILEP_HAND1_AXE_OF_WOE;
    case UNRAND_DARK_MAUL:                    return TILEP_HAND1_DARK_MAUL;
    case UNRAND_ARC_BLADE:                    return TILEP_HAND1_ARC_BLADE;
    case UNRAND_SPELLBINDER:                  return TILEP_HAND1_SPELLBINDER;
    case UNRAND_ORDER:                        return TILEP_HAND1_ORDER;
    case UNRAND_FIRESTARTER:                  return TILEP_HAND1_FIRESTARTER;
    case UNRAND_MAJIN:                        return TILEP_HAND1_MAJIN;
    case UNRAND_GYRE:                         return TILEP_HAND1_GYRE;
    case UNRAND_FROSTBITE:                    return TILEP_HAND1_FROSTBITE;
    case UNRAND_THERMIC_ENGINE:               return TILEP_HAND1_THERMIC_ENGINE;
    case UNRAND_RIFT:                         return TILEP_HAND1_RIFT;
    case UNRAND_WOODCUTTERS_AXE:              return TILEP_HAND1_AXE_SHORT;
    case UNRAND_THROATCUTTER:                 return TILEP_HAND1_THROATCUTTER;
    case UNRAND_MEEK:                         return TILEP_HAND1_STAFF_MAGE2;
    case UNRAND_CONDEMNATION:                 return TILEP_HAND1_CONDEMNATION;
    case UNRAND_LOCHABER_AXE:                 return TILEP_HAND1_LOCHABER_AXE;
    case UNRAND_FORCE_LANCE:                  return TILEP_HAND1_FORCE_LANCE;
    case UNRAND_HOLY_AXE:                     return TILEP_HAND1_HOLY_AXE;
    case UNRAND_MULE:                         return TILEP_HAND1_MULE;
    // HAND2
    case UNRAND_WUCAD_MU:                     return TILEP_HAND2_ORB_OF_WUCAD_MU;
    case UNRAND_DISPATER:                     return TILEP_HAND2_ORB_OF_DISPATER;
    case UNRAND_IGNORANCE:                    return TILEP_HAND2_TOWER_SHIELD_OF_IGNORANCE;
    case UNRAND_BULLSEYE:                     return TILEP_HAND2_KITE_SHIELD_BULLSEYE;
    case UNRAND_RESISTANCE:                   return TILEP_HAND2_KITE_SHIELD_OF_RESISTANCE;
    case UNRAND_GONG:                         return TILEP_HAND2_KITE_SHIELD_GONG;
    case UNRAND_WARLOCK_MIRROR:               return TILEP_HAND2_BUCKLER_WARLOCK;
    case UNRAND_BATTLE:                       return TILEP_HAND2_ORB_OF_BATTLE;
    case UNRAND_STORM_QUEEN:                  return TILEP_HAND2_KITE_SHIELD_STORM_QUEEN;
    // HELM
    case UNRAND_DYROVEPREVA:                  return TILEP_HELM_DYROVEPREVA;
    case UNRAND_BEAR_SPIRIT:                  return TILEP_HELM_BEAR;
    case UNRAND_HOOD_ASSASSIN:                return TILEP_HELM_HOOD_ASSASSIN;
    case UNRAND_DRAGONMASK:                   return TILEP_HELM_ART_DRAGONHELM;
    case UNRAND_ALCHEMIST:                    return TILEP_HELM_TURBAN_PURPLE;
    case UNRAND_PONDERING:                    return TILEP_HELM_WIZARD_BLUEGREEN;
    case UNRAND_HIGH_COUNCIL:                 return TILEP_HELM_WIZARD_LIGHTGREEN;
    case UNRAND_ETHERIC_CAGE:                 return TILEP_HELM_ETHERIC_CAGE;
    case UNRAND_ETERNAL_TORMENT:              return TILEP_HELM_ETERNAL_TORMENT;
    default: return 0;
    }
}

