#pragma once

/**********************************************************************
 * WARNING!
 *
 * This file is automatically generated. Do not edit this file directly;
 * instead edit art-data.txt to modify unrandart data, or util/art-data.pl
 * if this file is not being generated to your taste.
 *
 * Ignoring these warnings and editing this file directly will cause you
 * to be hunted down and eaten by dire rattlesnakes.
 **********************************************************************/

#define NUM_UNRANDARTS 135

enum unrand_type
{
    UNRAND_START = 180,
    UNRAND_DUMMY1 = UNRAND_START,
    UNRAND_SINGING_SWORD,               // Singing Sword
    UNRAND_TROG,                        // Wrath of Trog
    UNRAND_VARIABILITY,                 // mace of Variability
    UNRAND_PRUNE,                       // glaive of Prune
    UNRAND_POWER,                       // sword of Power
    UNRAND_OLGREB,                      // staff of Olgreb
    UNRAND_WUCAD_MU,                    // crystal ball of Wucad Mu
    UNRAND_VAMPIRES_TOOTH,              // Vampire's Tooth
    UNRAND_CURSES,                      // scythe of Curses
    UNRAND_TORMENT,                     // sceptre of Torment
    UNRAND_ZONGULDROK,                  // sword of Zonguldrok
    UNRAND_CEREBOV,                     // sword of Cerebov
    UNRAND_DISPATER,                    // orb of Dispater
    UNRAND_ASMODEUS,                    // sceptre of Asmodeus
    UNRAND_FAERIE,                      // faerie dragon scales
    UNRAND_BLOODBANE,                   // demon blade "Bloodbane"
    UNRAND_FLAMING_DEATH,               // scimitar of Flaming Death
    UNRAND_BRILLIANCE,                  // eveningstar "Brilliance"
    UNRAND_LEECH,                       // demon blade "Leech"
    UNRAND_CHILLY_DEATH,                // dagger of Chilly Death
    UNRAND_MORG,                        // dagger "Morg"
    UNRAND_FINISHER,                    // scythe "Finisher"
    UNRAND_PUNK,                        // greatsling "Punk"
    UNRAND_ZEPHYR,                      // longbow "Zephyr"
    UNRAND_SKULLCRUSHER,                // giant club "Skullcrusher"
    UNRAND_GUARD,                       // glaive of the Guard
    UNRAND_ZEALOT_SWORD,                // zealot's sword
    UNRAND_DAMNATION,                   // arbalest "Damnation"
    UNRAND_DOOM_KNIGHT,                 // sword of the Doom Knight
    UNRAND_EOS,                         // morningstar "Eos"
    UNRAND_BOTONO,                      // spear of the Botono
    UNRAND_OCTOPUS_KING,                // trident of the Octopus King
    UNRAND_ARGA,                        // mithril axe "Arga"
    UNRAND_ELEMENTAL_STAFF,             // Elemental Staff
    UNRAND_SNIPER,                      // heavy crossbow "Sniper"
    UNRAND_PIERCER,                     // longbow "Piercer"
    UNRAND_BLOWGUN_ASSASSIN,            // blowgun of the Assassin
    UNRAND_WYRMBANE,                    // lance "Wyrmbane"
    UNRAND_SPRIGGANS_KNIFE,             // Spriggan's Knife
    UNRAND_PLUTONIUM_SWORD,             // plutonium sword
    UNRAND_UNDEADHUNTER,                // great mace "Undeadhunter"
    UNRAND_SNAKEBITE,                   // whip "Snakebite"
    UNRAND_ACCURACY,                    // knife of Accuracy
    UNRAND_CRYSTAL_SPEAR,               // Lehudib's crystal spear
    UNRAND_CAPTAIN,                     // captain's cutlass
    UNRAND_STORM_BOW,                   // storm bow
    UNRAND_IGNORANCE,                   // tower shield of Ignorance
    UNRAND_AUGMENTATION,                // robe of Augmentation
    UNRAND_THIEF,                       // cloak of the Thief
    UNRAND_BULLSEYE,                    // tower shield "Bullseye"
    UNRAND_DYROVEPREVA,                 // crown of Dyrovepreva
    UNRAND_BEAR_SPIRIT,                 // hat of the Bear Spirit
    UNRAND_MISFORTUNE,                  // robe of Misfortune
    UNRAND_FLASH,                       // cloak of Flash
    UNRAND_HOOD_ASSASSIN,               // hood of the Assassin
    UNRAND_LEAR,                        // Lear's hauberk
    UNRAND_ZHOR,                        // skin of Zhor
    UNRAND_SALAMANDER,                  // salamander hide armour
    UNRAND_WAR,                         // gauntlets of War
    UNRAND_RESISTANCE,                  // shield of Resistance
    UNRAND_FOLLY,                       // robe of Folly
    UNRAND_MAXWELL,                     // Maxwell's patent armour
    UNRAND_DRAGONMASK,                  // mask of the Dragon
    UNRAND_NIGHT,                       // robe of Night
    UNRAND_DRAGON_KING,                 // scales of the Dragon King
    UNRAND_ALCHEMIST,                   // hat of the Alchemist
    UNRAND_FENCERS,                     // fencer's gloves
    UNRAND_STARLIGHT,                   // cloak of Starlight
    UNRAND_RATSKIN_CLOAK,               // ratskin cloak
    UNRAND_GONG,                        // shield of the Gong
    UNRAND_AIR,                         // amulet of the Air
    UNRAND_SHADOWS,                     // ring of Shadows
    UNRAND_CEKUGOB,                     // amulet of Cekugob
    UNRAND_FOUR_WINDS,                  // amulet of the Four Winds
    UNRAND_BLOODLUST,                   // necklace of Bloodlust
    UNRAND_HARE,                        // ring of the Hare
    UNRAND_TORTOISE,                    // ring of the Tortoise
    UNRAND_MAGE,                        // ring of the Mage
    UNRAND_SHIELDING,                   // brooch of Shielding
    UNRAND_RCLOUDS,                     // robe of Clouds
    UNRAND_PONDERING,                   // hat of Pondering
    UNRAND_DEMON_AXE,                   // obsidian axe
    UNRAND_LIGHTNING_SCALES,            // lightning scales
    UNRAND_BLACK_KNIGHT_HORSE,          // Black Knight's barding
    UNRAND_VITALITY,                    // amulet of Vitality
    UNRAND_AUTUMN_KATANA,               // autumn katana
    UNRAND_DEVASTATOR,                  // shillelagh "Devastator"
    UNRAND_DRAGONSKIN,                  // dragonskin cloak
    UNRAND_OCTOPUS_KING_RING,           // ring of the Octopus King
    UNRAND_WOE,                         // Axe of Woe
    UNRAND_MOON_TROLL_LEATHER_ARMOUR,   // moon troll leather armour
    UNRAND_FINGER_AMULET,               // macabre finger necklace
    UNRAND_SPIDER,                      // boots of the spider
    UNRAND_DARK_MAUL,                   // dark maul
    UNRAND_HIGH_COUNCIL,                // hat of the High Council
    UNRAND_ARC_BLADE,                   // arc blade
    UNRAND_SPELLBINDER,                 // demon whip "Spellbinder"
    UNRAND_ORDER,                       // lajatang of Order
    UNRAND_FIRESTARTER,                 // great mace "Firestarter"
    UNRAND_ORANGE_CRYSTAL_PLATE_ARMOUR, // orange crystal plate armour
    UNRAND_MAJIN,                       // Majin-Bo
    UNRAND_GYRE,                        // pair of quick blades "Gyre" and "Gimble"
    UNRAND_ETHERIC_CAGE,                // Maxwell's etheric cage
    UNRAND_ETERNAL_TORMENT,             // crown of Eternal Torment
    UNRAND_VINES,                       // robe of Vines
    UNRAND_KRYIAS,                      // Kryia's mail coat
    UNRAND_FROSTBITE,                   // frozen axe "Frostbite"
    UNRAND_TALOS,                       // armour of Talos
    UNRAND_WARLOCK_MIRROR,              // warlock's mirror
    UNRAND_INVISIBILITY,                // amulet of invisibility
    UNRAND_THERMIC_ENGINE,              // Maxwell's thermic engine
    UNRAND_RIFT,                        // demon trident "Rift"
    UNRAND_BATTLE,                      // sphere of Battle
    UNRAND_EMBRACE,                     // Cigotuvi's embrace
    UNRAND_SEVEN_LEAGUE_BOOTS,          // seven-league boots
    UNRAND_POWER_GLOVES,                // Mad Mage's Maulers
    UNRAND_DREAMSHARD_NECKLACE,         // dreamshard necklace
    UNRAND_DELATRAS_GLOVES,             // Delatra's gloves
    UNRAND_WOODCUTTERS_AXE,             // woodcutter's axe
    UNRAND_THROATCUTTER,                // Throatcutter
    UNRAND_MEEK,                        // staff of the Meek
    UNRAND_CONDEMNATION,                // trishula "Condemnation"
    UNRAND_ELEMENTAL_VULNERABILITY,     // amulet of Elemental Vulnerability
    UNRAND_MOUNTAIN_BOOTS,              // mountain boots
    UNRAND_LOCHABER_AXE,                // Lochaber axe
    UNRAND_HERMITS_PENDANT,             // Hermit's Pendant
    UNRAND_SLICK_SLIPPERS,              // slick slippers
    UNRAND_FORCE_LANCE,                 // Force Lance
    UNRAND_HOLY_AXE,                    // consecrated labrys
    UNRAND_VICTORY,                     // toga "Victory"
    UNRAND_STORM_QUEEN,                 // Storm Queen's Shield
    UNRAND_DREAMDUST_NECKLACE,          // dreamdust necklace
    UNRAND_MULE,                        // hand cannon "Mule"
    UNRAND_DUMMY2,                      // DUMMY UNRANDART 2
    UNRAND_LAST = UNRAND_DUMMY2

};
