/*
 * This file is autogenerated, see util/species-gen.py and dat/species/ for
 * more info.
 */
#pragma once

static species_group species_groups[] =
{

    {
        "Simple",
        coord_def(0, 0),
        50,
        { SP_HILL_ORC, SP_MINOTAUR, SP_MERFOLK, SP_GARGOYLE, SP_BASE_DRACONIAN, SP_TROLL, SP_DEEP_ELF, SP_ARMATAUR, SP_GNOLL }
    },

    {
        "Intermediate",
        coord_def(1, 0),
        20,
        { SP_HUMAN, SP_KOBOLD, SP_DEMONSPAWN, SP_DJINNI, SP_SPRIGGAN, SP_GHOUL, SP_TENGU, SP_ONI, SP_BARACHI }
    },

    {
        "Advanced",
        coord_def(2, 0),
        20,
        { SP_VINE_STALKER, SP_VAMPIRE, SP_DEMIGOD, SP_FORMICID, SP_NAGA, SP_OCTOPODE, SP_FELID, SP_MUMMY }
    },
};
