/* Definitions for unrandom artefacts. */

/**********************************************************************
 * WARNING!
 *
 * This file is automatically generated. Do not edit this file directly;
 * instead edit art-data.txt to modify unrandart data, or util/art-data.pl
 * if this file is not being generated to your taste.
 *
 * If the unrandart_entry struct is changed or a new artefact property is
 * added to artefact_prop_type, then change art-data.pl so that the
 * art-data.h file it produces matches up with the new structure.
 *
 * Ignoring these warnings and editing this file directly will cause you
 * to be hunted down and eaten by dire tarantulas.
 **********************************************************************/

#pragma once
#ifndef ART_FUNC_H
#error "art-func.h must be included before art-data.h"
#endif

/* UNRAND_DUMMY1 */
{
    "DUMMY UNRANDART 1", "DUMMY UNRANDART 1", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_UNASSIGNED, 250, 
    OBJ_UNASSIGNED, 250, -1, 
    250, 0, BLACK, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_SINGING_SWORD */
{
    "Singing Sword", "Singing Sword", nullptr, 
    "sonic wave", "Sonic Wave: It radiates damaging sonic waves as it strikes, especially in combat involving dangerous or numerous foes.", nullptr, 
    OBJ_WEAPONS, WPN_DOUBLE_SWORD, 
    OBJ_UNASSIGNED, 250, -1, 
    +11, 0, ETC_GOLD, 1000, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _SINGING_SWORD_equip, _SINGING_SWORD_unequip, _SINGING_SWORD_world_reacts, _SINGING_SWORD_melee_effects, nullptr, nullptr, 
},

/* UNRAND_TROG */
{
    "Wrath of Trog", "Wrath of Trog", nullptr, 
    nullptr, nullptr, "It causes slowness and exhaustion when equipped.\nIt extends the wielder's berserk rage when killing foes.", 
    OBJ_WEAPONS, WPN_BATTLEAXE, 
    OBJ_WEAPONS, WPN_EXECUTIONERS_AXE, -1, 
    +8, 0, ETC_BLOOD, 800, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ANTIMAGIC, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 50, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _TROG_equip, _TROG_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_VARIABILITY */
{
    "mace of Variability", "mace of Variability", nullptr, 
    "chaos arc", "Chaos Arc: It occasionally unleashes arcs of chaos on nearby creatures upon striking a foe.", nullptr, 
    OBJ_WEAPONS, WPN_GREAT_MACE, 
    OBJ_WEAPONS, OBJ_RANDOM, -1, 
    +7, 0, ETC_RANDOM, 600, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_CHAOS, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _VARIABILITY_melee_effects, nullptr, nullptr, 
},

/* UNRAND_PRUNE */
{
    "glaive of Prune", "glaive of Prune", nullptr, 
    "Prune", nullptr, "Prune:     It halves damage taken while paralysed, petrified or unconscious.", 
    OBJ_WEAPONS, WPN_GLAIVE, 
    OBJ_UNASSIGNED, 250, -1, 
    +12, 0, LIGHTMAGENTA, 0, 
    UNRAND_FLAG_CHAOTIC, 
    {
        SPWPN_FREEZING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _PRUNE_equip, _PRUNE_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_POWER */
{
    "sword of Power", "sword of Power", nullptr, 
    "lifebolt", "Lifebolt:  It occasionally discharges a powerful but inaccurate bolt of energy upon striking a foe, with increased chance the greater the wielder's current health.", nullptr, 
    OBJ_WEAPONS, WPN_GREAT_SWORD, 
    OBJ_UNASSIGNED, 250, -1, 
    +9, 0, RED, 800, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _POWER_equip, nullptr, nullptr, _POWER_melee_effects, nullptr, nullptr, 
},

/* UNRAND_OLGREB */
{
    "staff of Olgreb", "staff of Olgreb", nullptr, 
    "rPois∞", "Envenom: If the wielder is skilled in Evocations, they can envenom those struck by it, dealing poison damage which bypasses armour.", "Radiate: It can be activated via the 'a'bility menu to radiate toxic energy, with effectiveness depending on Evocations skill.\nAlch: It enhances your alchemy magic.\nrPois∞: It grants immunity to poison.", 
    OBJ_WEAPONS, WPN_STAFF, 
    OBJ_UNASSIGNED, 250, -1, 
    +9, 0, ETC_POISON, 1000, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _OLGREB_equip, _OLGREB_unequip, nullptr, _OLGREB_melee_effects, nullptr, nullptr, 
},

/* UNRAND_WUCAD_MU */
{
    "crystal ball of Wucad Mu", "crystal ball of Wucad Mu", nullptr, 
    "*channel", nullptr, "*Channel:  It often returns the magic spent to cast spells, but lowers their success rate. It always returns the magic spent on miscasts.", 
    OBJ_ARMOUR, ARM_ORB, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_MAGIC, 1000, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _WUCAD_MU_equip, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_VAMPIRES_TOOTH */
{
    "Vampire's Tooth", "Vampire's Tooth", nullptr, 
    "megavamp", "Megavamp:  It occasionally heals its wielder for the full amount of damage dealt when it wounds a living foe.", nullptr, 
    OBJ_WEAPONS, WPN_QUICK_BLADE, 
    OBJ_UNASSIGNED, 250, SPWPN_VAMPIRISM, 
    +8, 0, ETC_BONE, 600, 
    UNRAND_FLAG_SKIP_EGO, 
    {
        SPWPN_VAMPIRISM, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _VAMPIRES_TOOTH_equip, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_CURSES */
{
    "scythe of Curses", "scythe of Curses", "scythe", 
    "curses,", "Curses:    It inflicts powerful necromantic curses on any living foe it strikes.", nullptr, 
    OBJ_WEAPONS, WPN_HALBERD, 
    OBJ_WEAPONS, WPN_BARDICHE, -1, 
    +13, 0, ETC_DEATH, 800, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_DRAINING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        +5, 0, 0, 0, +1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _CURSES_equip, nullptr, nullptr, _CURSES_melee_effects, nullptr, nullptr, 
},

/* UNRAND_TORMENT */
{
    "sceptre of Torment", "sceptre of Torment", nullptr, 
    "torment", "Torment:   It occasionally torments all nearby living foes when it strikes in combat.", nullptr, 
    OBJ_WEAPONS, WPN_EVENINGSTAR, 
    OBJ_UNASSIGNED, 250, -1, 
    +7, 0, ETC_GOLD, 1200, 
    UNRAND_FLAG_EVIL, 
    {
        SPWPN_PAIN, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _TORMENT_equip, nullptr, nullptr, _TORMENT_melee_effects, nullptr, nullptr, 
},

/* UNRAND_ZONGULDROK */
{
    "sword of Zonguldrok", "sword of Zonguldrok", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_DOUBLE_SWORD, 
    OBJ_UNASSIGNED, 250, SPWPN_PAIN, 
    +9, 0, ETC_BONE, 800, 
    UNRAND_FLAG_EVIL, 
    {
        SPWPN_REAPING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _ZONGULDROK_equip, nullptr, nullptr, _ZONGULDROK_melee_effects, nullptr, nullptr, 
},

/* UNRAND_CEREBOV */
{
    "sword of Cerebov", "great serpentine sword", "flamberge", 
    nullptr, "Hellfire:  It temporarily reduces the fire resistance of those it strikes.", nullptr, 
    OBJ_WEAPONS, WPN_GREAT_SWORD, 
    OBJ_UNASSIGNED, 250, -1, 
    +6, 0, ETC_FIRE, 0, 
    UNRAND_FLAG_EVIL | UNRAND_FLAG_NOGEN, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, +1, +1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _CEREBOV_melee_effects, nullptr, nullptr, 
},

/* UNRAND_DISPATER */
{
    "orb of Dispater", "orb of Dispater", nullptr, 
    "+Damnation", nullptr, "+Damnation: It grants the ability to hurl damnation at the cost of health and magic, with strength depending on Evocations skill.", 
    OBJ_ARMOUR, ARM_ORB, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, LIGHTRED, 0, 
    UNRAND_FLAG_EVIL | UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 5, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_ASMODEUS */
{
    "sceptre of Asmodeus", "ruby sceptre", nullptr, 
    nullptr, nullptr, "Fire Summon: It may summon demons of flame and damnation when striking foes.", 
    OBJ_WEAPONS, WPN_EVENINGSTAR, 
    OBJ_UNASSIGNED, 250, -1, 
    +13, 0, ETC_BLOOD, 0, 
    UNRAND_FLAG_EVIL | UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _ASMODEUS_melee_effects, nullptr, nullptr, 
},

/* UNRAND_FAERIE */
{
    "faerie dragon scales", "faerie dragon scales", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_ACID_DRAGON_ARMOUR, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, ETC_JEWEL, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_BLOODBANE */
{
    "demon blade \"Bloodbane\"", "demon blade \"Bloodbane\"", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_DEMON_BLADE, 
    OBJ_UNASSIGNED, 250, -1, 
    +8, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_DRAINING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 5, 0, 
        0, 0, 0, 0, -1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_FLAMING_DEATH */
{
    "scimitar of Flaming Death", "scimitar of Flaming Death", nullptr, 
    "sticky flame,", nullptr, nullptr, 
    OBJ_WEAPONS, WPN_SCIMITAR, 
    OBJ_UNASSIGNED, 250, -1, 
    +6, 0, ETC_FIRE, 0, 
    UNRAND_FLAG_NOGEN | UNRAND_FLAG_SKIP_EGO, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        2, -1, 0, 1, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _FLAMING_DEATH_equip, _FLAMING_DEATH_unequip, nullptr, _FLAMING_DEATH_melee_effects, nullptr, nullptr, 
},

/* UNRAND_BRILLIANCE */
{
    "eveningstar \"Brilliance\"", "eveningstar \"Brilliance\"", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_EVENINGSTAR, 
    OBJ_UNASSIGNED, 250, -1, 
    +1, 0, ETC_HOLY, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_HOLY_WRATH, 5, 0, 0, 5, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_LEECH */
{
    "demon blade \"Leech\"", "demon blade \"Leech\"", nullptr, 
    "evervamp,", "Evervamp:  It heals its wielder for a portion of the damage dealt every time it strikes a living foe.", nullptr, 
    OBJ_WEAPONS, WPN_DEMON_BLADE, 
    OBJ_UNASSIGNED, 250, -1, 
    +8, 0, ETC_DARK, 0, 
    UNRAND_FLAG_SKIP_EGO, 
    {
        SPWPN_VAMPIRISM, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _LEECH_equip, nullptr, nullptr, _LEECH_melee_effects, nullptr, nullptr, 
},

/* UNRAND_CHILLY_DEATH */
{
    "dagger of Chilly Death", "dagger of Chilly Death", nullptr, 
    "flash freeze,", nullptr, nullptr, 
    OBJ_WEAPONS, WPN_DAGGER, 
    OBJ_UNASSIGNED, 250, -1, 
    +9, 0, ETC_ICE, 0, 
    UNRAND_FLAG_NOGEN | UNRAND_FLAG_SKIP_EGO, 
    {
        SPWPN_FREEZING, 0, 0, 0, 0, 0, 
        -1, 2, 0, 1, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _CHILLY_DEATH_equip, _CHILLY_DEATH_unequip, nullptr, _CHILLY_DEATH_melee_effects, nullptr, nullptr, 
},

/* UNRAND_MORG */
{
    "dagger \"Morg\"", "dagger \"Morg\"", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_DAGGER, 
    OBJ_UNASSIGNED, 250, -1, 
    +4, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_PAIN, 0, 0, 0, 5, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_FINISHER */
{
    "scythe \"Finisher\"", "scythe \"Finisher\"", "scythe", 
    "execute", "Execute:   It may instantly slay those it strikes, especially weaker foes.", nullptr, 
    OBJ_WEAPONS, WPN_HALBERD, 
    OBJ_WEAPONS, WPN_BARDICHE, -1, 
    +5, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        +5, 0, 0, 0, +1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _FINISHER_melee_effects, nullptr, nullptr, 
},

/* UNRAND_PUNK */
{
    "greatsling \"Punk\"", "greatsling \"Punk\"", "greatsling", 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_SLING, 
    OBJ_UNASSIGNED, 250, SPWPN_NORMAL, 
    +3, 0, ETC_SLIME, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ACID, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, +3, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_ZEPHYR */
{
    "longbow \"Zephyr\"", "longbow \"Zephyr\"", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_LONGBOW, 
    OBJ_UNASSIGNED, 250, -1, 
    +8, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 0, 0, 3, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_SKULLCRUSHER */
{
    "giant club \"Skullcrusher\"", "giant club \"Skullcrusher\"", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_GIANT_CLUB, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 7, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_GUARD */
{
    "glaive of the Guard", "glaive of the Guard", nullptr, 
    "spectral,", "Spectral:  When it strikes, its spirit leaps out and fights alongside the wielder.", nullptr, 
    OBJ_WEAPONS, WPN_GLAIVE, 
    OBJ_WEAPONS, WPN_BARDICHE, -1, 
    +5, 0, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ELECTROCUTION, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, _GUARD_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_ZEALOT_SWORD */
{
    "zealot's sword", "zealot's sword", nullptr, 
    "Zealotry,", nullptr, "Zealotry:  Whenever the wielder enters a berserk rage, their allies are berserked alongside them.", 
    OBJ_WEAPONS, WPN_EUDEMON_BLADE, 
    OBJ_UNASSIGNED, 250, SPWPN_HOLY_WRATH, 
    +10, 0, ETC_HOLY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HOLY_WRATH, 0, 3, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 20, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_DAMNATION */
{
    "arbalest \"Damnation\"", "arbalest \"Damnation\"", nullptr, 
    "damnation", "Damnation: Any ammunition fired from it explodes in a burst of damnation on striking a foe, dealing damage which bypasses armour.", nullptr, 
    OBJ_WEAPONS, WPN_ARBALEST, 
    OBJ_UNASSIGNED, 250, SPWPN_FLAMING, 
    +6, 0, ETC_FIRE, 800, 
    UNRAND_FLAG_EVIL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, _DAMNATION_launch, nullptr, 
},

/* UNRAND_DOOM_KNIGHT */
{
    "sword of the Doom Knight", "sword of the Doom Knight", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_GREAT_SWORD, 
    OBJ_UNASSIGNED, 250, -1, 
    +13, 0, BLUE, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_PAIN, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_EOS */
{
    "morningstar \"Eos\"", "morningstar \"Eos\"", nullptr, 
    "Halo", nullptr, "Halo:      It grants its wielder a halo, revealing invisible creatures and increasing accuracy against all within it other than the wielder.", 
    OBJ_WEAPONS, WPN_MORNINGSTAR, 
    OBJ_UNASSIGNED, 250, -1, 
    +10, 0, ETC_JEWEL, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ELECTROCUTION, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _EOS_equip, _EOS_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_BOTONO */
{
    "spear of the Botono", "spear of the Botono", nullptr, 
    "Hex", nullptr, nullptr, 
    OBJ_WEAPONS, WPN_SPEAR, 
    OBJ_UNASSIGNED, 250, SPWPN_PAIN, 
    +6, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_REAPING, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, -6, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_OCTOPUS_KING */
{
    "trident of the Octopus King", "trident of the Octopus King", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_TRIDENT, 
    OBJ_UNASSIGNED, 250, -1, 
    +8, 0, ETC_WATER, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VENOM, 0, 0, 0, 0, 0, 
        0, 0, 1, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _OCTOPUS_KING_equip, nullptr, _OCTOPUS_KING_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_ARGA */
{
    "mithril axe \"Arga\"", "mithril axe \"Arga\"", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_BROAD_AXE, 
    OBJ_UNASSIGNED, 250, -1, 
    +8, 0, WHITE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_ELEMENTAL_STAFF */
{
    "Elemental Staff", "Elemental Staff", nullptr, 
    "ele,", "Ele:       It enhances your fire, ice, earth and air magic. If skilled in Evocations, you can discharge powerful blasts of elemental energy when striking with it.", nullptr, 
    OBJ_WEAPONS, WPN_STAFF, 
    OBJ_WEAPONS, WPN_LAJATANG, SPWPN_FREEZING, 
    +3, 0, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 3, 0, 0, 0, 0, 
        1, 1, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _ELEMENTAL_STAFF_melee_effects, nullptr, nullptr, 
},

/* UNRAND_SNIPER */
{
    "heavy crossbow \"Sniper\"", "heavy crossbow \"Sniper\"", "heavy crossbow", 
    "Acc+∞", nullptr, "Acc+∞:     It never misses its target.", 
    OBJ_WEAPONS, WPN_TRIPLE_CROSSBOW, 
    OBJ_UNASSIGNED, 250, -1, 
    +27, 0, ETC_DARK, 800, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HEAVY, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        +2, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_PIERCER */
{
    "longbow \"Piercer\"", "longbow \"Piercer\"", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_LONGBOW, 
    OBJ_UNASSIGNED, 250, -1, 
    +7, 0, CYAN, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_PENETRATION, 0, -2, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_BLOWGUN_ASSASSIN */
{
    "blowgun of the Assassin", "blowgun of the Assassin", nullptr, 
    "stab,", nullptr, nullptr, 
    OBJ_WEAPONS, WPN_BLOWGUN, 
    OBJ_WEAPONS, WPN_LONGBOW, -1, 
    +6, 0, ETC_DEATH, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 2, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_WYRMBANE */
{
    "lance \"Wyrmbane\"", "lance \"Wyrmbane\"", "lance", 
    "slay drac,", "Slay Drac: It inflicts extra damage against dragons and draconians.", nullptr, 
    OBJ_WEAPONS, WPN_SPEAR, 
    OBJ_WEAPONS, WPN_DEMON_TRIDENT, SPWPN_FLAMING, 
    +8, 0, LIGHTGREEN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 3, 0, 0, 0, 0, 
        1, 1, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, +2, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _WYRMBANE_equip, nullptr, nullptr, _WYRMBANE_melee_effects, nullptr, nullptr, 
},

/* UNRAND_SPRIGGANS_KNIFE */
{
    "Spriggan's Knife", "Spriggan's Knife", "knife", 
    "stab,", nullptr, "Stab:      It is more effective when stabbing unaware enemies, sometimes treating them as though they were completely helpless.", 
    OBJ_WEAPONS, WPN_DAGGER, 
    OBJ_UNASSIGNED, 250, -1, 
    +7, 0, LIGHTCYAN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 4, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_PLUTONIUM_SWORD */
{
    "plutonium sword", "plutonium sword", nullptr, 
    nullptr, "Mutate:    It occasionally inflicts wild transmutation effects on those it strikes, inflicting malmutation or extra damage, or polymorphing them into a new form.", nullptr, 
    OBJ_WEAPONS, WPN_TRIPLE_SWORD, 
    OBJ_UNASSIGNED, 250, SPWPN_CHAOS, 
    +11, 0, ETC_MUTAGENIC, 1000, 
    UNRAND_FLAG_CHAOTIC, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        1, 0, 0, 0, -1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _PLUTONIUM_SWORD_melee_effects, nullptr, nullptr, 
},

/* UNRAND_UNDEADHUNTER */
{
    "great mace \"Undeadhunter\"", "great mace \"Undeadhunter\"", nullptr, 
    "deathbane,", "Deathbane: It inflicts significantly more damage against the undead.", nullptr, 
    OBJ_WEAPONS, WPN_GREAT_MACE, 
    OBJ_UNASSIGNED, 250, SPWPN_HOLY_WRATH, 
    +7, 0, LIGHTGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _UNDEADHUNTER_melee_effects, nullptr, nullptr, 
},

/* UNRAND_SNAKEBITE */
{
    "whip \"Snakebite\"", "whip \"Snakebite\"", nullptr, 
    "curare,", "Curare:    It occasionally inflicts asphyxiating poison on those it strikes, dealing poison damage and causing slowness.", nullptr, 
    OBJ_WEAPONS, WPN_WHIP, 
    OBJ_WEAPONS, WPN_DEMON_WHIP, -1, 
    +8, 0, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_VENOM, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _SNAKEBITE_melee_effects, nullptr, nullptr, 
},

/* UNRAND_ACCURACY */
{
    "knife of Accuracy", "knife of Accuracy", "knife", 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_DAGGER, 
    OBJ_UNASSIGNED, 250, -1, 
    +27, 0, LIGHTCYAN, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_CRYSTAL_SPEAR */
{
    "Lehudib's crystal spear", "Lehudib's crystal spear", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_SPEAR, 
    OBJ_UNASSIGNED, 250, -1, 
    +6, 0, GREEN, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 3, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_CAPTAIN */
{
    "captain's cutlass", "captain's cutlass", "cutlass", 
    "disarm", "Disarm:    It may disarm weapon-wielding foes when striking them, dealing extra damage in the process.", nullptr, 
    OBJ_WEAPONS, WPN_RAPIER, 
    OBJ_UNASSIGNED, 250, -1, 
    +7, 0, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_SPEED, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _CAPTAIN_melee_effects, nullptr, nullptr, 
},

/* UNRAND_STORM_BOW */
{
    "storm bow", "storm bow", nullptr, 
    "penet", "Penet:     Any ammunition fired by it passes through the targets it hits, potentially hitting all targets in its path until it reaches maximum range.", nullptr, 
    OBJ_WEAPONS, WPN_LONGBOW, 
    OBJ_UNASSIGNED, 250, -1, 
    +8, 0, BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ELECTROCUTION, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_IGNORANCE */
{
    "tower shield of Ignorance", "tower shield of Ignorance", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_TOWER_SHIELD, 
    OBJ_UNASSIGNED, 250, -1, 
    +10, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, -4, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_AUGMENTATION */
{
    "robe of Augmentation", "robe of Augmentation", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_ROBE, 
    OBJ_UNASSIGNED, 250, -1, 
    +4, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 4, 4, 4, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_THIEF */
{
    "cloak of the Thief", "cloak of the Thief", nullptr, 
    "*Fog", nullptr, "*Fog:      It may release a thick cloud of smoke when the wearer is hurt.", 
    OBJ_ARMOUR, ARM_CLOAK, 
    OBJ_UNASSIGNED, 250, SPARM_INVISIBILITY, 
    +2, 0, ETC_DARK, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, -2, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_BULLSEYE */
{
    "tower shield \"Bullseye\"", "tower shield \"Bullseye\"", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_TOWER_SHIELD, 
    OBJ_UNASSIGNED, 250, -1, 
    +15, 0, RED, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 0, -5, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_DYROVEPREVA */
{
    "crown of Dyrovepreva", "crown of Dyrovepreva", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_HAT, 
    OBJ_UNASSIGNED, 250, SPARM_SEE_INVISIBLE, 
    +3, 0, ETC_JEWEL, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 2, 0, 
        0, 0, 1, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_BEAR_SPIRIT */
{
    "hat of the Bear Spirit", "hat of the Bear Spirit", nullptr, 
    "Bear,", "Bear:      Going berserk makes the wearer exceptionally tough, and they are slowed for a shorter time afterward.", nullptr, 
    OBJ_ARMOUR, ARM_HAT, 
    OBJ_UNASSIGNED, 250, -1, 
    +2, 0, DARKGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_SPIRIT_SHIELD, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 20, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_MISFORTUNE */
{
    "robe of Misfortune", "robe of Misfortune", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_ROBE, 
    OBJ_UNASSIGNED, 250, SPARM_PONDEROUSNESS, 
    5, 0, LIGHTMAGENTA, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 5, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 1, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_FLASH */
{
    "cloak of Flash", "cloak of Flash", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_CLOAK, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, ETC_FLASH, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 0, 4, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_HOOD_ASSASSIN */
{
    "hood of the Assassin", "hood of the Assassin", nullptr, 
    "Detect Stab+", nullptr, "Detect:    It allows the wearer to sense nearby creatures.\nStab+:     It allows the wearer to make particularly effective stabbing attacks against helpless or unaware enemies with any weapon.", 
    OBJ_ARMOUR, ARM_HAT, 
    OBJ_UNASSIGNED, 250, SPARM_SEE_INVISIBLE, 
    +2, 0, BROWN, 600, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 2, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_LEAR */
{
    "Lear's hauberk", "Lear's hauberk", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_CHAIN_MAIL, 
    OBJ_ARMOUR, ARM_PLATE_ARMOUR, -1, 
    18, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_ZHOR */
{
    "skin of Zhor", "skin of Zhor", nullptr, 
    "*Englaciate", nullptr, "*Englaciate: It radiates cold, occasionally slowing all nearby creatures who are not resistant to cold.", 
    OBJ_ARMOUR, ARM_ANIMAL_SKIN, 
    OBJ_ARMOUR, ARM_STEAM_DRAGON_ARMOUR, -1, 
    +4, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 3, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, _ZHOR_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_SALAMANDER */
{
    "salamander hide armour", "salamander hide armour", nullptr, 
    "Flames, rFlCloud", nullptr, "Flames:    It surrounds you with flame clouds and enhances your fire magic.\nrFlCloud:  It grants immunity to flame clouds.", 
    OBJ_ARMOUR, ARM_LEATHER_ARMOUR, 
    OBJ_UNASSIGNED, 250, SPARM_FIRE_RESISTANCE, 
    +3, 0, ETC_FIRE, 0, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        2, -2, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _SALAMANDER_equip, _SALAMANDER_unequip, _SALAMANDER_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_WAR */
{
    "gauntlets of War", "gauntlets of War", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_GLOVES, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 5, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_RESISTANCE */
{
    "shield of Resistance", "shield of Resistance", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_KITE_SHIELD, 
    OBJ_UNASSIGNED, 250, -1, 
    +2, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        2, 2, 0, 0, 0, 2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_FOLLY */
{
    "robe of Folly", "robe of Folly", nullptr, 
    "Brill Will-∞", nullptr, "Brill:     It increases the power of your magical spells and halves their MP cost (rounding up).\nWill-∞:    It reduces your willpower to zero.", 
    OBJ_ARMOUR, ARM_ROBE, 
    OBJ_UNASSIGNED, 250, -1, 
    4, 0, LIGHTGREY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 8, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_MAXWELL */
{
    "Maxwell's patent armour", "Maxwell's patent armour", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_PLATE_ARMOUR, 
    OBJ_UNASSIGNED, 250, -1, 
    +15, 0, LIGHTGREEN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_DRAGONMASK */
{
    "mask of the Dragon", "mask of the Dragon", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_HAT, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_SHIMMER_BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 3, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_NIGHT */
{
    "robe of Night", "robe of Night", nullptr, 
    "Dark", nullptr, "Dark:      It shrouds the wearer in darkness, reducing the range at which they can see and be seen by others.", 
    OBJ_ARMOUR, ARM_ROBE, 
    OBJ_UNASSIGNED, 250, -1, 
    +5, 0, ETC_DARK, 600, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _NIGHT_equip, _NIGHT_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_DRAGON_KING */
{
    "scales of the Dragon King", "scales of the Dragon King", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_GOLD_DRAGON_ARMOUR, 
    OBJ_UNASSIGNED, 250, -1, 
    +9, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_ALCHEMIST */
{
    "hat of the Alchemist", "hat of the Alchemist", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_HAT, 
    OBJ_UNASSIGNED, 250, -1, 
    -2, 0, LIGHTMAGENTA, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        1, 1, 1, 1, 1, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_FENCERS */
{
    "fencer's gloves", "fencer's gloves", nullptr, 
    "Riposte", nullptr, "Riposte:   It allows the wearer to riposte with melee weapons, swiftly retaliating against missed or blocked melee attacks.", 
    OBJ_ARMOUR, ARM_GLOVES, 
    OBJ_UNASSIGNED, 250, -1, 
    +0, 0, WHITE, 400, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 3, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _FENCERS_equip, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_STARLIGHT */
{
    "cloak of Starlight", "cloak of Starlight", nullptr, 
    "*Dazzle", nullptr, "*Dazzle:   It may blind those who miss an attack against the wearer in melee combat.", 
    OBJ_ARMOUR, ARM_CLOAK, 
    OBJ_UNASSIGNED, 250, -1, 
    +1, 0, ETC_ICE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 4, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, -2, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_RATSKIN_CLOAK */
{
    "ratskin cloak", "ratskin cloak", nullptr, 
    "*Rats", nullptr, "*Rats:     When the wearer is hurt, rats may emerge from it to assist them.", 
    OBJ_ARMOUR, ARM_CLOAK, 
    OBJ_UNASSIGNED, 250, -1, 
    +2, 0, ETC_BEOGH, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, -1, -1, 1, 
        0, 0, 0, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_GONG */
{
    "shield of the Gong", "shield of the Gong", nullptr, 
    "Loud", nullptr, "Loud:      It is deafeningly noisy when blocking attacks.", 
    OBJ_ARMOUR, ARM_KITE_SHIELD, 
    OBJ_ARMOUR, ARM_TOWER_SHIELD, -1, 
    +18, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, -5, 0, 0, 0, 
        0, 0, 0, 0, 1, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _GONG_melee_effects, nullptr, nullptr, 
},

/* UNRAND_AIR */
{
    "amulet of the Air", "amulet of the Air", nullptr, 
    "Inacc Air", nullptr, "Inacc:     It reduces the accuracy of your attacks and spells.\nAir:       It enhances your air magic.", 
    OBJ_JEWELLERY, AMU_NOTHING, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_SHADOWS */
{
    "ring of Shadows", "ring of Shadows", nullptr, 
    "Umbra", nullptr, "Umbra:     It surrounds you with an aura of shadow, increasing your stealth and reducing the accuracy of all others within it.", 
    OBJ_JEWELLERY, RING_STEALTH, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_DARK, 400, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _SHADOWS_equip, _SHADOWS_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_CEKUGOB */
{
    "amulet of Cekugob", "amulet of Cekugob", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, AMU_ACROBAT, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_SILVER, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        0, 1, 1, 0, 0, 0, 
        0, 0, 1, 1, 2, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_FOUR_WINDS */
{
    "amulet of the Four Winds", "amulet of the Four Winds", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, AMU_NOTHING, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_POISON, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 3, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_BLOODLUST */
{
    "necklace of Bloodlust", "necklace of Bloodlust", nullptr, 
    "Fury", nullptr, "Fury:      It extends the wearer's berserk rage when killing foes.", 
    OBJ_JEWELLERY, AMU_NOTHING, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_BLOOD, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, -3, 0, 
        0, 0, 0, 0, 0, 2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 50, 0, 
        0, 0, 6, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_HARE */
{
    "ring of the Hare", "ring of the Hare", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, RING_EVASION, 
    OBJ_UNASSIGNED, 250, -1, 
    +10, 0, ETC_POISON, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_TORTOISE */
{
    "ring of the Tortoise", "ring of the Tortoise", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, RING_PROTECTION, 
    OBJ_UNASSIGNED, 250, -1, 
    +8, 0, ETC_GOLD, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_MAGE */
{
    "ring of the Mage", "ring of the Mage", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, RING_WIZARDRY, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_ENCHANT, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_SHIELDING */
{
    "brooch of Shielding", "brooch of Shielding", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, AMU_GUARDIAN_SPIRIT, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_MAGIC, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        +8, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_RCLOUDS */
{
    "robe of Clouds", "robe of Clouds", nullptr, 
    "*Thunder rCloud", nullptr, "*Thunder:  It occasionally creates storm clouds above nearby enemies.\nrCloud:    It grants its wearer immunity to clouds.", 
    OBJ_ARMOUR, ARM_ROBE, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, ETC_MIST, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, _RCLOUDS_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_PONDERING */
{
    "hat of Pondering", "hat of Pondering", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_HAT, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_PONDEROUSNESS, 0, 0, 0, +5, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, +10, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_DEMON_AXE */
{
    "obsidian axe", "obsidian axe", nullptr, 
    "demonic, Mesm", "Demonic:   It occasionally summons demons to assist the wielder when it strikes in combat.", "Mesm:      Its wielder is mesmerised by any visible foes, and it cannot be unequipped while any foes are visible.", 
    OBJ_WEAPONS, WPN_BROAD_AXE, 
    OBJ_UNASSIGNED, 250, SPWPN_PAIN, 
    +16, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_EVIL, 
    {
        SPWPN_DRAINING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, _DEMON_AXE_unequip, _DEMON_AXE_world_reacts, _DEMON_AXE_melee_effects, nullptr, nullptr, 
},

/* UNRAND_LIGHTNING_SCALES */
{
    "lightning scales", "lightning scales", nullptr, 
    "swift,", nullptr, "Swift:     It allows the wearer to cover ground more swiftly.", 
    OBJ_ARMOUR, ARM_BARDING, 
    OBJ_UNASSIGNED, 250, -1, 
    +6, 0, ETC_ELECTRICITY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _LIGHTNING_SCALES_equip, _LIGHTNING_SCALES_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_BLACK_KNIGHT_HORSE */
{
    "Black Knight's barding", "Black Knight's barding", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_BARDING, 
    OBJ_UNASSIGNED, 250, -1, 
    +10, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_EVIL, 
    {
        SPARM_PONDEROUSNESS, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, _BLACK_KNIGHT_HORSE_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_VITALITY */
{
    "amulet of Vitality", "amulet of Vitality", nullptr, 
    "RegenMP++", nullptr, nullptr, 
    OBJ_JEWELLERY, AMU_MANA_REGENERATION, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_MUTAGENIC, 1000, 
    UNRAND_FLAG_SKIP_EGO, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 2, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_AUTUMN_KATANA */
{
    "autumn katana", "autumn katana", "katana", 
    "manifold assault", "Manifold Assault: It sometimes launches melee attacks against multiple visible enemies.", nullptr, 
    OBJ_WEAPONS, WPN_LONG_SWORD, 
    OBJ_WEAPONS, WPN_DOUBLE_SWORD, -1, 
    +8, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        -2, 0, 0, +2, +4, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _AUTUMN_KATANA_melee_effects, nullptr, nullptr, 
},

/* UNRAND_DEVASTATOR */
{
    "shillelagh \"Devastator\"", "shillelagh \"Devastator\"", "shillelagh", 
    "shatter", "Shatter:   It releases a powerful concussive burst when it strikes, dealing extra damage to the target and all other creatures adjacent to them.", nullptr, 
    OBJ_WEAPONS, WPN_CLUB, 
    OBJ_WEAPONS, WPN_EVENINGSTAR, SPWPN_HEAVY, 
    +6, 0, WHITE, 600, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, +3, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _DEVASTATOR_equip, nullptr, nullptr, _DEVASTATOR_melee_effects, nullptr, nullptr, 
},

/* UNRAND_DRAGONSKIN */
{
    "dragonskin cloak", "opalescent scaly cloak", nullptr, 
    nullptr, nullptr, "Avatar's Aegis: It grants the wearer a chance to resist fire, cold, poison, electricity, acid, and negative energy.", 
    OBJ_ARMOUR, ARM_CLOAK, 
    OBJ_UNASSIGNED, 250, -1, 
    +4, 0, ETC_HEAL, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _DRAGONSKIN_equip, _DRAGONSKIN_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_OCTOPUS_KING_RING */
{
    "ring of the Octopus King", "ring of the Octopus King", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, RING_FIRST_RING, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_WATER, 0, 
    UNRAND_FLAG_UNIDED, 
    {
        0, +2, +2, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, +2, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        +2, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_WOE */
{
    "Axe of Woe", "Axe of Woe", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_EXECUTIONERS_AXE, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_BLOOD, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _WOE_melee_effects, nullptr, nullptr, 
},

/* UNRAND_MOON_TROLL_LEATHER_ARMOUR */
{
    "moon troll leather armour", "moon troll leather armour", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_TROLL_LEATHER_ARMOUR, 
    OBJ_UNASSIGNED, 250, -1, 
    +5, 0, ETC_SHIMMER_BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_SPIRIT_SHIELD, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, +5, 
        0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_FINGER_AMULET */
{
    "macabre finger necklace", "macabre finger necklace", nullptr, 
    "Finger+", nullptr, "Finger+:   It enables you to equip an extra ring.", 
    OBJ_JEWELLERY, AMU_NOTHING, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_BONE, 400, 
    UNRAND_FLAG_EVIL, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, _FINGER_AMULET_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_SPIDER */
{
    "boots of the spider", "boots of the spider", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_BOOTS, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, LIGHTMAGENTA, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_JUMPING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_DARK_MAUL */
{
    "dark maul", "dark maul", "maul", 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_GREAT_MACE, 
    OBJ_UNASSIGNED, 250, -1, 
    +10, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HEAVY, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        +7, 0, 0, +2, +20, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_HIGH_COUNCIL */
{
    "hat of the High Council", "hat of the High Council", nullptr, 
    "Wiz-", nullptr, nullptr, 
    OBJ_ARMOUR, ARM_HAT, 
    OBJ_UNASSIGNED, 250, -1, 
    +2, 0, LIGHTGREEN, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_ARCHMAGI, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, -1, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_ARC_BLADE */
{
    "arc blade", "arc blade", nullptr, 
    "discharge,", "Discharge: It occasionally unleashes powerful arcs of lightning upon striking a foe. These may arc to other adjacent creatures (including the wielder, but dealing reduced damage to them) before grounding out.", nullptr, 
    OBJ_WEAPONS, WPN_RAPIER, 
    OBJ_WEAPONS, WPN_QUICK_BLADE, SPWPN_ELECTROCUTION, 
    +8, 0, ETC_ELECTRICITY, 600, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _ARC_BLADE_equip, _ARC_BLADE_unequip, nullptr, _ARC_BLADE_melee_effects, nullptr, nullptr, 
},

/* UNRAND_SPELLBINDER */
{
    "demon whip \"Spellbinder\"", "demon whip \"Spellbinder\"", nullptr, 
    "disrupt,", "Disrupt:   It unleashes wild and unpredictable magical effects upon striking a wizard or a creature with magical abilities.", nullptr, 
    OBJ_WEAPONS, WPN_DEMON_WHIP, 
    OBJ_UNASSIGNED, 250, -1, 
    +5, 0, ETC_ENCHANT, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_ANTIMAGIC, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _SPELLBINDER_melee_effects, nullptr, nullptr, 
},

/* UNRAND_ORDER */
{
    "lajatang of Order", "lajatang of Order", nullptr, 
    "silver,", "Silver:    It inflicts extra damage upon those it strikes, and deals substantially increased damage to chaotic, mutated and magically transformed beings.", nullptr, 
    OBJ_WEAPONS, WPN_LAJATANG, 
    OBJ_UNASSIGNED, 250, SPWPN_HOLY_WRATH, 
    +7, 0, ETC_SILVER, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _ORDER_melee_effects, nullptr, nullptr, 
},

/* UNRAND_FIRESTARTER */
{
    "great mace \"Firestarter\"", "great mace \"Firestarter\"", nullptr, 
    "immolate, rFlCloud", "Immolate:  It fills those it strikes with an explosive inner flame.", "rFlCloud:  It grants immunity to clouds of flame.", 
    OBJ_WEAPONS, WPN_GREAT_MACE, 
    OBJ_UNASSIGNED, 250, -1, 
    +7, 0, RED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        2, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _FIRESTARTER_equip, _FIRESTARTER_unequip, nullptr, _FIRESTARTER_melee_effects, nullptr, nullptr, 
},

/* UNRAND_ORANGE_CRYSTAL_PLATE_ARMOUR */
{
    "orange crystal plate armour", "orange crystal plate armour", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_CRYSTAL_PLATE_ARMOUR, 
    OBJ_UNASSIGNED, 250, SPWPN_NORMAL, 
    8, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_ARCHMAGI, 0, 0, 0, 3, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_MAJIN */
{
    "Majin-Bo", "Majin-Bo", "bo", 
    "spellvamp,", "Spellvamp: It heals its wielder for a portion of the damage dealt when they wound a living foe with it or with a spell, but its wielder's spells cost health as well as magical power.", nullptr, 
    OBJ_WEAPONS, WPN_STAFF, 
    OBJ_WEAPONS, WPN_LAJATANG, -1, 
    +6, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_SKIP_EGO, 
    {
        SPWPN_VAMPIRISM, 0, 0, 0, 6, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 6, 
        0, 0, 0, -4, +6, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _MAJIN_equip, _MAJIN_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_GYRE */
{
    "pair of quick blades \"Gyre\" and \"Gimble\"", "pair of quick blades \"Gyre\" and \"Gimble\"", "pair of quick blades", 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_QUICK_BLADE, 
    OBJ_UNASSIGNED, 250, SPWPN_FREEZING, 
    8, 0, ETC_ENCHANT, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_PROTECTION, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_ETHERIC_CAGE */
{
    "Maxwell's etheric cage", "Maxwell's etheric cage", nullptr, 
    "RegenMP+", nullptr, nullptr, 
    OBJ_ARMOUR, ARM_HELMET, 
    OBJ_UNASSIGNED, 250, -1, 
    +0, 0, ETC_ELECTRICITY, 400, 
    UNRAND_FLAG_CHAOTIC | UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, +4, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _ETHERIC_CAGE_equip, nullptr, _ETHERIC_CAGE_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_ETERNAL_TORMENT */
{
    "crown of Eternal Torment", "crown of Eternal Torment", nullptr, 
    "rTorment HP--", nullptr, nullptr, 
    OBJ_ARMOUR, ARM_HAT, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, ETC_DARK, 0, 
    UNRAND_FLAG_EVIL | UNRAND_FLAG_NOGEN, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 3, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _ETERNAL_TORMENT_equip, _ETERNAL_TORMENT_unequip, _ETERNAL_TORMENT_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_VINES */
{
    "robe of Vines", "robe of Vines", nullptr, 
    "NoPotionHeal", nullptr, "NoPotionHeal: Its wearer cannot be healed by potions.", 
    OBJ_ARMOUR, ARM_ROBE, 
    OBJ_UNASSIGNED, 250, -1, 
    +1, 0, GREEN, 800, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 4, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _VINES_equip, _VINES_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_KRYIAS */
{
    "Kryia's mail coat", "Kryia's mail coat", nullptr, 
    "PotionHeal*2", nullptr, "PotionHeal*2: Potions heal its wearer twice as much.", 
    OBJ_ARMOUR, ARM_SCALE_MAIL, 
    OBJ_UNASSIGNED, 250, -1, 
    +7, 0, LIGHTCYAN, 600, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _KRYIAS_equip, _KRYIAS_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_FROSTBITE */
{
    "frozen axe \"Frostbite\"", "frozen axe \"Frostbite\"", nullptr, 
    "freezing cloud,", "Freezing Cloud: It occasionally leaves clouds of freezing vapour upon striking a foe, and grants immunity to clouds of freezing vapour.", nullptr, 
    OBJ_WEAPONS, WPN_EXECUTIONERS_AXE, 
    OBJ_UNASSIGNED, 250, -1, 
    +8, 0, ETC_ICE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FREEZING, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 1, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _FROSTBITE_melee_effects, nullptr, nullptr, 
},

/* UNRAND_TALOS */
{
    "armour of Talos", "armour of Talos", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_ARMOUR, ARM_PLATE_ARMOUR, 
    OBJ_UNASSIGNED, 250, -1, 
    +12, 0, ETC_FIRE, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        SPARM_PONDEROUSNESS, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_WARLOCK_MIRROR */
{
    "warlock's mirror", "warlock's mirror", nullptr, 
    "omnireflect", "Omnireflect: It can block and reflect piercing ranged attacks and magical attacks against the wielder's willpower.", nullptr, 
    OBJ_ARMOUR, ARM_BUCKLER, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, ETC_SILVER, 400, 
    UNRAND_FLAG_SKIP_EGO, 
    {
        SPARM_REFLECTION, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_INVISIBILITY */
{
    "amulet of invisibility", "amulet of invisibility", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, AMU_NOTHING, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, WHITE, 0, 
    UNRAND_FLAG_NOGEN, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_THERMIC_ENGINE */
{
    "Maxwell's thermic engine", "Maxwell's thermic engine", nullptr, 
    "freeze, rev,", "Freeze:    It freezes victims, dealing an additional one-quarter of any damage that pierces defenders' armour. It may also slow down cold-blooded creatures.\nRev:       It becomes more effective when it hits something. This effect fades over time.", nullptr, 
    OBJ_WEAPONS, WPN_DOUBLE_SWORD, 
    OBJ_UNASSIGNED, 250, -1, 
    +2, 0, ETC_VEHUMET, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _THERMIC_ENGINE_equip, _THERMIC_ENGINE_unequip, _THERMIC_ENGINE_world_reacts, _THERMIC_ENGINE_melee_effects, nullptr, nullptr, 
},

/* UNRAND_RIFT */
{
    "demon trident \"Rift\"", "demon trident \"Rift\"", nullptr, 
    "reach+", "Reach+:    It can reach especially far, and its reaching attacks ignore other creatures in the way.", nullptr, 
    OBJ_WEAPONS, WPN_DEMON_TRIDENT, 
    OBJ_UNASSIGNED, 250, -1, 
    +8, 0, ETC_WARP, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_DISTORTION, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_BATTLE */
{
    "sphere of Battle", "sphere of Battle", nullptr, 
    nullptr, nullptr, "Battle: It summons a battlesphere in combat, with strength depending on Conjurations skill.\nDestructive: It enhances your destructive magic, and weakens non-destructive magic.", 
    OBJ_ARMOUR, ARM_ORB, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_MAGIC, 800, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, _BATTLE_unequip, _BATTLE_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_EMBRACE */
{
    "Cigotuvi's embrace", "Cigotuvi's embrace", nullptr, 
    "Corpsefed rMiasma", nullptr, "Corpsefed: It gathers nearby corpses to temporarily increase the armour it provides.\nrMiasma:   It protects you from foul pestilence.", 
    OBJ_ARMOUR, ARM_LEATHER_ARMOUR, 
    OBJ_UNASSIGNED, 250, -1, 
    +4, 0, ETC_UNHOLY, 0, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_EVIL, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, _EMBRACE_unequip, _EMBRACE_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_SEVEN_LEAGUE_BOOTS */
{
    "seven-league boots", "seven-league boots", nullptr, 
    "Rampage+∞", nullptr, "Rampage+∞: When moving toward enemies, its wearer moves as far as possible, alerting their target en route.", 
    OBJ_ARMOUR, ARM_BOOTS, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, ETC_ENCHANT, 400, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _SEVEN_LEAGUE_BOOTS_equip, _SEVEN_LEAGUE_BOOTS_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_POWER_GLOVES */
{
    "Mad Mage's Maulers", "Mad Mage's Maulers", nullptr, 
    "Infuse+∞ VampMP", nullptr, "Infuse+∞:  It empowers its wearer's blows with all of their magic.\nVampMP:    Blows struck in melee replenish the wearer's magic.", 
    OBJ_ARMOUR, ARM_GLOVES, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, ETC_MAGIC, 400, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _POWER_GLOVES_equip, _POWER_GLOVES_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_DREAMSHARD_NECKLACE */
{
    "dreamshard necklace", "dreamshard necklace", nullptr, 
    "*Dream", nullptr, "*Dream:    It absorbs a single lethal wound into itself, holding its wearer just short of death and releasing dream-creatures to guard them.", 
    OBJ_JEWELLERY, AMU_ACROBAT, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_SILVER, 2000, 
    UNRAND_FLAG_SPECIAL, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _DREAMSHARD_NECKLACE_equip, _DREAMSHARD_NECKLACE_unequip, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_DELATRAS_GLOVES */
{
    "Delatra's gloves", "Delatra's gloves", nullptr, 
    "ID++", nullptr, "ID++:      It heals its wearer when they drink unknown potions, and restores their MP when they read unknown scrolls.", 
    OBJ_ARMOUR, ARM_GLOVES, 
    OBJ_UNASSIGNED, 250, -1, 
    +1, 0, BLUE, 100, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_WOODCUTTERS_AXE */
{
    "woodcutter's axe", "woodcutter's axe", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_WEAPONS, WPN_BATTLEAXE, 
    OBJ_UNASSIGNED, 250, -1, 
    5, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        -7, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_THROATCUTTER */
{
    "Throatcutter", "Throatcutter", nullptr, 
    "coup de grace", "Coup de Grace: It may instantly kill foes which have little health.", nullptr, 
    OBJ_WEAPONS, WPN_LONG_SWORD, 
    OBJ_WEAPONS, WPN_SCIMITAR, -1, 
    7, 0, LIGHTRED, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_DRAINING, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _THROATCUTTER_melee_effects, nullptr, nullptr, 
},

/* UNRAND_MEEK */
{
    "staff of the Meek", "staff of the Meek", nullptr, 
    "meekguard", "Meekguard: It provides extra protection to wielders with little health.", nullptr, 
    OBJ_WEAPONS, WPN_QUARTERSTAFF, 
    OBJ_UNASSIGNED, 250, -1, 
    7, 0, WHITE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_PROTECTION, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_CONDEMNATION */
{
    "trishula \"Condemnation\"", "trishula \"Condemnation\"", nullptr, 
    "anguish,", "Anguish:   It makes its victims' attacks reflect back on them.", nullptr, 
    OBJ_WEAPONS, WPN_TRISHULA, 
    OBJ_UNASSIGNED, 250, SPWPN_HOLY_WRATH, 
    8, 0, ETC_HOLY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HOLY_WRATH, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 1, 0, 0, 1, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _CONDEMNATION_equip, _CONDEMNATION_unequip, nullptr, _CONDEMNATION_melee_effects, nullptr, nullptr, 
},

/* UNRAND_ELEMENTAL_VULNERABILITY */
{
    "amulet of Elemental Vulnerability", "amulet of Elemental Vulnerability", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, AMU_NOTHING, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_VEHUMET, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 8, 0, 0, 0, 0, 
        -2, -2, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_MOUNTAIN_BOOTS */
{
    "mountain boots", "mountain boots", nullptr, 
    "steadfast,", "Steadfast: It prevents involuntary movement, except for blinking, teleportation, or banishment.", nullptr, 
    OBJ_ARMOUR, ARM_BOOTS, 
    OBJ_UNASSIGNED, 250, -1, 
    +3, 0, ETC_MOUNTAIN, 0, 
    UNRAND_FLAG_SPECIAL, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 1, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_LOCHABER_AXE */
{
    "Lochaber axe", "Lochaber axe", "Lochaber axe", 
    "reach-cleave, Poleaxe", "Reach-Cleave: It can be evoked to extend its reach, and strikes at all foes within reach, dealing less damage to those not targeted.", "Poleaxe:   It uses either Axes or Polearms skill, whichever is higher.", 
    OBJ_WEAPONS, WPN_BARDICHE, 
    OBJ_UNASSIGNED, 250, -1, 
    +5, 0, ETC_IRON, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        +1, 0, 0, -1, +1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 1, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_HERMITS_PENDANT */
{
    "Hermit's Pendant", "Hermit's Pendant", nullptr, 
    "Invo=14 Evo=0", "Invo=14:   It sets your Invocations skill to 14.\nEvo=0:     It sets your Evocations skill to 0.", nullptr, 
    OBJ_JEWELLERY, AMU_FAITH, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, BROWN, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, +5, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_SLICK_SLIPPERS */
{
    "slick slippers", "slick slippers", nullptr, 
    "slick, slippery,", "Slick:     Its wearer cannot be constricted, engulfed, netted or webbed.\nSlippery:  Its wearer slips away from damaging melee attacks, pulling the attacker onward.", nullptr, 
    OBJ_ARMOUR, ARM_BOOTS, 
    OBJ_UNASSIGNED, 250, -1, 
    +2, 0, ETC_DITHMENOS, 270, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 4, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_FORCE_LANCE */
{
    "Force Lance", "Force Lance", "lance", 
    "knockback,", "Knockback: It sometimes drives back enemies it hits.", nullptr, 
    OBJ_WEAPONS, WPN_SPEAR, 
    OBJ_WEAPONS, WPN_DEMON_TRIDENT, -1, 
    +5, 0, ETC_DISJUNCTION, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HEAVY, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, +2, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _FORCE_LANCE_melee_effects, nullptr, nullptr, 
},

/* UNRAND_HOLY_AXE */
{
    "consecrated labrys", "consecrated labrys", "labrys", 
    "Valiant", nullptr, "Valiant:   It becomes more powerful as more dangerous foes come into view.", 
    OBJ_WEAPONS, WPN_BROAD_AXE, 
    OBJ_UNASSIGNED, 250, -1, 
    +4, 0, ETC_HOLY, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_HOLY_WRATH, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        1, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, +1, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 1, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, _HOLY_AXE_world_reacts, nullptr, nullptr, nullptr, 
},

/* UNRAND_VICTORY */
{
    "toga \"Victory\"", "toga \"Victory\"", nullptr, 
    "*Victory", nullptr, "*Victory:  When the wearer kills a threatening monster, it has a chance to gain +1 AC, +1 Slay, and +1 Int, capping at +7. When the wearer uses a scroll or a potion with a hostile monster in sight, its bonuses reset to +0. Unequipping it also resets its bonuses to +0.", 
    OBJ_ARMOUR, ARM_ROBE, 
    OBJ_UNASSIGNED, 250, -1, 
    +0, 0, LIGHTCYAN, 600, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, +0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, +0, 0, 0, 0, 
        0, 0, 1, 0, 0, 
        0, 0, 0, 0, 1, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    _VICTORY_equip, _VICTORY_unequip, _VICTORY_world_reacts, nullptr, nullptr, _VICTORY_death_effects, 
},

/* UNRAND_STORM_QUEEN */
{
    "Storm Queen's Shield", "Storm Queen's Shield", nullptr, 
    "shock,", "Shock:     When it blocks an attack, it may electrocute the attacker. This works even against foes who are a short distance away.", nullptr, 
    OBJ_ARMOUR, ARM_KITE_SHIELD, 
    OBJ_ARMOUR, ARM_TOWER_SHIELD, -1, 
    +5, 0, BLUE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPARM_NORMAL, 0, 0, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 1, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, _STORM_QUEEN_melee_effects, nullptr, nullptr, 
},

/* UNRAND_DREAMDUST_NECKLACE */
{
    "dreamdust necklace", "dreamdust necklace", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_JEWELLERY, AMU_ACROBAT, 
    OBJ_UNASSIGNED, 250, -1, 
    0, 0, ETC_SILVER, 0, 
    UNRAND_FLAG_SPECIAL | UNRAND_FLAG_NOGEN, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_MULE */
{
    "hand cannon \"Mule\"", "hand cannon \"Mule\"", nullptr, 
    "backblast,", "Backblast: When fired, it often launches its wielder backwards.", nullptr, 
    OBJ_WEAPONS, WPN_HAND_CANNON, 
    OBJ_UNASSIGNED, 250, -1, 
    7, 0, ETC_INCARNADINE, 0, 
    UNRAND_FLAG_NONE, 
    {
        SPWPN_FLAMING, 0, 0, 0, 0, 0, 
        1, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

/* UNRAND_DUMMY2 */
{
    "DUMMY UNRANDART 2", "DUMMY UNRANDART 2", nullptr, 
    nullptr, nullptr, nullptr, 
    OBJ_UNASSIGNED, 250, 
    OBJ_UNASSIGNED, 250, -1, 
    250, 0, BLACK, 0, 
    UNRAND_FLAG_NONE, 
    {
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 
        0, 0, 0, 0, 0, 
        0, 0, 0, 0, 
        
    },
    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, 
},

