name: index_seed
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v4

      - name: Install crawl
        run: |
          sudo apt update
          sudo apt -y install crawl
          #- name: Setup tmate session
          #uses: mxschmitt/action-tmate@v3
      - name: Start Index
        run: |
          #sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.so.0 /usr/lib/liblua5.1.so.5.1
          chmod 777 $GITHUB_WORKSPACE/crawl/crawl-ref/source/crawl
          cd $GITHUB_WORKSPACE/seed-search
          $GITHUB_WORKSPACE/crawl/crawl-ref/source/crawl -builddb 
          ./scripts/pre-gen-all.sh
      - name: Upload 
        timeout-minutes: 720
        run: |
          # Note: the following account information will not work on GHES
          mkdir -p ~/.ssh/
          echo "${ID_RSA}" > ~/.ssh/id_rsa
          echo "${ID_RSA_PUB}" > ~/.ssh/id_rsa.pub
          echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
          chmod 400 ~/.ssh/*
          git config user.name "fish4terrisa-MSDSM"
          git config user.email "flyingfish.msdsm@gmail.com"
          git remote rm origin
          git remote add origin git@github.com:fish4terrisa-MSDSM/crawl-seed.git
          git add .
          git commit -m "ac updated"
          git push -u origin flyingfish
          echo done
          #- uses: EndBug/add-and-commit@v9
          #with:
          #default_author: user_info
          #message: "updated new jsons"
        env:
          ID_RSA: ${{secrets.ID_RSA}}
          KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
          ID_RSA_PUB: ${{secrets.ID_RSA_PUB}}
